### ISSUE TITLE
excludedPackages doesn't alter percent coverage reported

### ISSUE THREAD

**Issue by myio561** [scoverage/scoverage-maven-plugin#25]
I've been trying to exclude code from packages that don't contain business logic (domain entities, etc). However, the percentage of coverage never varies regardless how many packages I exclude. Am I setting the configuration incorrectly? Below is my plugin setting from my POM:

```
            <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>${scoverage.plugin.version}</version>
                <configuration>
                    <highlighting>true</highlighting>
                    <minimumCoverage>50</minimumCoverage>
                    <failOnMinimumCoverage>true</failOnMinimumCoverage>
                    <scalaVersion>${scala.version}</scalaVersion>
                     <!--Exclude packages that don't contain business logic-->
                    <excludedPackages>com.nextera.fim.ventus.controller.*;com.nextera.fim.ventus.search.*;com.nextera.fim.ventus.domain.*;com.nextera.fim.ventus.views.*</excludedPackages>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal> <!-- or integration-check -->
                        </goals>
                        <phase>prepare-package</phase> <!-- or any other phase -->
                    </execution>
                </executions>
            </plugin>

```

My build fails due to inadequate code coverage and the percentage covered reported never varies:

```
[INFO] 
[INFO] <<< scoverage-maven-plugin:1.1.0:check (default-cli) @ ventus <<<
[INFO] 
[INFO] --- scoverage-maven-plugin:1.1.0:check (default-cli) @ ventus ---
[ERROR] [scoverage] Coverage is below minimum [1.35% < 50.00%]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.476s
[INFO] Finished at: Tue Nov 24 10:53:42 EST 2015
[INFO] Final Memory: 27M/329M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scoverage:scoverage-maven-plugin:1.1.0:check (default-cli) on project ventus: Coverage minimum was not reached -> [Help 1]
```

**Comment by gslowikowski** [comment]
Did you clean project after adding/changing `excludedPackages` parameter?

**Comment by gslowikowski** [comment]
Additionally, this is regular expression. I would write it as follows:
```
<excludedPackages>com\.nextera\.fim\.ventus\.(controller|search|domain|views)</excludedPackages>
```

**Comment by gslowikowski** [comment]
It works for me on simple test project.

**Comment by myio561** [comment]
Yes, I did run clean between test. I tried using the RegEx but when I use that I get an exception when it tries to parse it.

```
[INFO] C:\Users\gxs0onr\git\wind\ventus\src\main\scala:-1: info: compiling
[INFO] Compiling 16 source files to C:\Users\gxs0onr\git\wind\ventus\target\scoverage-classes at 1448390286547
[ERROR] error: java.util.regex.PatternSyntaxException: Unclosed group near index 38
[INFO] com\.nextera\.fim\.ventus\.(controller
[INFO]                                       ^
[ERROR] 	at java.util.regex.Pattern.error(Pattern.java:1955)
[INFO] 	at java.util.regex.Pattern.accept(Pattern.java:1813)
```

**Comment by myio561** [comment]
I think I was misinterpreting the output before. If I change my exclusion pattern to avoid the parsing error the coverage results look good. I couldn't get scoverage to work using  ```(controller|search)```
I had to resort to a more explicit list:
```                    
<excludedPackages>(empty);com\.nextera\.fim;.*\.controller;.*\.search;.*\.domain;.*\.view</excludedPackages>
```

**Comment by gslowikowski** [comment]
I wonder, why pattern compilation failed. It works for me. What's your JDK version?

**Comment by gslowikowski** [comment]
To pass Scoverage parameters to `scala-maven-plugin` plugin I use [addScalacArgs](http://davidb.github.io/scala-maven-plugin/compile-mojo.html#addScalacArgs) project property.
As you can see, `scala-maven-plugin` used a pipe character to split parameters, so it splits your regexp parameter value.
I don't see any possibility to escape pipes.

I was testing with `sbt-compiler-maven-plugin`, that's why I had no errors.
