### ISSUE TITLE
Connection Timeout Issue

### ISSUE THREAD

**Issue by MatthewEdge** [scoverage/scoverage-maven-plugin#27]
When running Scoverage on a Jenkins build node at work, the build constantly fails on a Connection timed out error.

My scoverage Maven entry looks like the following:

            <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>1.1.1</version>
                <configuration>
                    <scalaVersion>2.10.4</scalaVersion>
                    <aggregate>true</aggregate>
                    <highlighting>true</highlighting>
                </configuration>
                <executions>
                    <execution>
                        <id>packageReport</id>
                        <phase>package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

For reference, here is the error I see when running maven with -X. Any ideas?

    java.net.ConnectException: Connection timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:649)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1103)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:997)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1511)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:646)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1300)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1267)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1164)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
	at scala.xml.factory.XMLLoader$class.loadXML(XMLLoader.scala:40)
	at scala.xml.XML$.loadXML(XML.scala:57)
	at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:47)
	at scala.xml.XML$.loadFile(XML.scala:57)
	at org.scoverage.plugin.SCoverageReportMojo.generateAggregatedReports(SCoverageReportMojo.java:434)
	at org.scoverage.plugin.SCoverageReportMojo.canGenerateReport(SCoverageReportMojo.java:266)
	at org.scoverage.plugin.SCoverageReportMojo.execute(SCoverageReportMojo.java:347)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.jvnet.hudson.maven3.launcher.Maven31Launcher.main(Maven31Launcher.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven31Main.launch(Maven31Main.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:134)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:69)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:328)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MatthewEdge** [comment]
Please let me know if any further information is needed. Thanks!

**Comment by gslowikowski** [comment]
Dtd file referenced by 'cobertura.xml' cannot be loaded for some reason.

**Comment by MatthewEdge** [comment]
Is it correct to say this DTD file is a network resource?

**Comment by gslowikowski** [comment]
There is a problem with reading DTD file referenced by `cobertura.xml` file.
```
<!DOCTYPE coverage SYSTEM "https://raw.githubusercontent.com/cobertura/cobertura/master/cobertura/src/site/htdocs/xml/coverage-04.dtd">
```

I have different error when working offline:
`java.net.UnknownHostException: raw.githubusercontent.com`
and this is reasonable. Why you have connection timeout, I don't know.

I will try to disable dtd resolving when opening `cobertura.xml`

**Comment by gslowikowski** [comment]
Can you try `1.2.0-SNAPSHOT` version of the plugin?

You will have to add:
```xml
            <repositories>
                <repository>
                    <id>sonatype-nexus-snapshots</id>
                    <name>Sonatype Nexus Snapshots</name>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
            </repositories>

            <pluginRepositories>
                <pluginRepository>
                    <id>sonatype-nexus-snapshots</id>
                    <name>Sonatype Nexus Snapshots</name>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </pluginRepository>
            </pluginRepositories>
```
to your `pom.xml` file.

**Comment by gslowikowski** [comment]
@MatthewEdge, did you try `1.2.0-SNAPSHOT`? Can this issue be closed?

**Comment by MatthewEdge** [comment]
So sorry for the delay! (Busy busy at work)

I will try this fix today. Thanks!

**Comment by ltcao** [comment]
hi!
we're behind a webproxy; we've set the proxy value in the settings.xml and that does not seem to be honored by the code. StackTrace goes as follows:

[ERROR] Server returned HTTP response code: 407 for URL: http://cobertura.sourceforge.net/xml/coverage-04.dtd
java.io.IOException: Server returned HTTP response code: 407 for URL: http://cobertura.sourceforge.net/xml/coverage-04.dtd

...

at scala.xml.factory.XMLLoader$class.loadXML(XMLLoader.scala:40)
	at scala.xml.XML$.loadXML(XML.scala:57)
	at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:47)
	at scala.xml.XML$.loadFile(XML.scala:57)
	at org.scoverage.plugin.SCoverageReportMojo.generateAggregatedReports(SCoverageReportMojo.java:444)
	at org.scoverage.plugin.SCoverageReportMojo.generate(SCoverageReportMojo.java:217)
	at org.scoverage.plugin.SCoverageReportMojo.execute(SCoverageReportMojo.java:367)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

-L

**Comment by gslowikowski** [comment]
New `1.2.0-SNAPSHOT` snapshot deployed, documentation site updated.

Try it, please.

**Comment by gslowikowski** [comment]
Nobody complains, so I assume, it's fixed.

**Comment by MatthewEdge** [comment]
Apologies for the slow replies. Issue was fixed. Thanks!

**Comment by ChengGit** [comment]
Hi, could you release that snapshot version? I am behind a proxy, so I could only use code that's in central maven repo..

**Comment by Lonelychair** [comment]
Hi. I have also the issue. It'is fixed with 1.2.0-SNAPSHOT very well.
Could it possible to release this snapshot version?
The fix is precious and necessary, ans it's not practical to work with a snapshot version.
Thank you very much.

**Comment by gslowikowski** [comment]
Give me a week or two.

**Comment by Lonelychair** [comment]
Great! Many thanks!
