### ISSUE TITLE
scoverage-report not exists

### ISSUE THREAD

**Issue by sriram-ranga** [scoverage/scoverage-maven-plugin#36]
I get the following error when i try to run publish scoverage XML and HTML report : 
Publishing Scoverage XML and HTML report ...
ERROR: Step ‘Publish Scoverage Report’ aborted due to exception: 
java.io.IOException:   ....\workspace\target\scala\scoverage-report not exists
	at org.jenkinsci.plugins.scoverage.ScoveragePublisher.copyReport(ScoveragePublisher.java:114)
	at org.jenkinsci.plugins.scoverage.ScoveragePublisher.perform(ScoveragePublisher.java:66)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE

I followed the steps as given in : https://wiki.jenkins-ci.org/display/JENKINS/Scoverage+Plugin

**Comment by gslowikowski** [comment]
Scoverage Report Directory parameter value for Maven project should be `target/site/scoverage`.

**Comment by sriram-ranga** [comment]
but I am trying to publish report for sbt project with the convention : "target/scala-2.xx/scoverage-report/scoverage.xml"

**Comment by gslowikowski** [comment]
You've created issue for Maven plugin. For SBT create ticket [here](https://github.com/scoverage/sbt-scoverage/issues).

**Comment by sriram-ranga** [comment]
Thanks gslowikowski ..sorry i missed that part
