### ISSUE TITLE
Write aggregate report throw exception: java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by allenn** [scoverage/scoverage-maven-plugin#45]
Hi, The commit   #29 has fixed file encoding issus in writing single report, but it is not fixed writing aggreagte report scenario. Below is the error stack when I use it in a mutiple module project and set `aggregate` to true

[ERROR] Input length = 1
java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.read(BufferedReader.java:175)
        at scala.io.BufferedSource$$anonfun$iter$1$$anonfun$apply$mcI$sp$1.apply$mcI$sp(BufferedSource.scala:38)
        at scala.io.Codec.wrap(Codec.scala:68)
        at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
        at scala.io.BufferedSource$$anonfun$iter$1.apply(BufferedSource.scala:38)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
        at scala.collection.Iterator$$anon$17.hasNext(Iterator.scala:511)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.io.Source.hasNext(Source.scala:226)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.io.Source.foreach(Source.scala:178)
        at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:320)
        at scala.io.Source.addString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)
        at scala.io.Source.mkString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:288)
        at scala.io.Source.mkString(Source.scala:178)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:290)
        at scala.io.Source.mkString(Source.scala:178)
        at scoverage.report.CodeGrid.source(CodeGrid.scala:80)
        at scoverage.report.CodeGrid.<init>(CodeGrid.scala:22)
        at scoverage.report.ScoverageHtmlWriter.filePage(ScoverageHtmlWriter.scala:84)
        at scoverage.report.ScoverageHtmlWriter.scoverage$report$ScoverageHtmlWriter$$writeFile(ScoverageHtmlWriter.scala:50)
        at scoverage.report.ScoverageHtmlWriter$$anonfun$scoverage$report$ScoverageHtmlWriter$$writePackage$1.apply(ScoverageHtmlWriter.scala:43)
        at scoverage.report.ScoverageHtmlWriter$$anonfun$scoverage$report$ScoverageHtmlWriter$$writePackage$1.apply(ScoverageHtmlWriter.scala:43)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scoverage.report.ScoverageHtmlWriter.scoverage$report$ScoverageHtmlWriter$$writePackage(ScoverageHtmlWriter.scala:43)
        at scoverage.report.ScoverageHtmlWriter$$anonfun$write$1.apply(ScoverageHtmlWriter.scala:33)
        at scoverage.report.ScoverageHtmlWriter$$anonfun$write$1.apply(ScoverageHtmlWriter.scala:33)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scoverage.report.ScoverageHtmlWriter.write(ScoverageHtmlWriter.scala:33)
        at org.scoverage.plugin.SCoverageReportMojo.generateAggregatedReports(SCoverageReportMojo.java:502)
        at org.scoverage.plugin.SCoverageReportMojo.generate(SCoverageReportMojo.java:221)
        at org.scoverage.plugin.SCoverageReportMojo.execute(SCoverageReportMojo.java:371)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by gslowikowski** [comment]
Fixed by #46
