### ISSUE TITLE
NoClassDefFoundError: scoverage/Invoker$

### ISSUE THREAD

**Issue by Diyakhi** [scoverage/scoverage-maven-plugin#60]
I am Diyakhi trying to scovrage for code coverage for one of our multi-project using maven build tool. I followed the steps given in the https://github.com/scoverage/scoverage-maven-plugin link and used maven plugin to build scoverage instrumented classes. When try to run tests on the instrumented class, I am getting the following error.
Also, included the scalac-scoverage-plugin_2.11-1.3.0.jar as a dependency while running test as mentioned in the link https://github.com/scoverage/scoverage-maven-plugin/issues/10 
and still getting the scoverage/Invoker$ error.
It is much appreciated, if you have any suggestion to fix the issue.
hanks

scoverage-maven-plugin version = 1.3.0
scala version=2.11

Error mesage
Exception in thread "main" java.lang.NoClassDefFoundError: scoverage/Invoker$
	at org.apache.spark.util.CommandLineUtils$class.$init$(CommandLineUtils.scala:33)
	at org.apache.spark.deploy.SparkSubmit$.<init>(SparkSubmit.scala:70)
	at org.apache.spark.deploy.SparkSubmit$.<clinit>(SparkSubmit.scala)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: scoverage.Invoker$
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by gslowikowski** [comment]
Hi @Diyakhi. Sorry for late reply. Reopen this issue if you still need help.
