### ISSUE TITLE
User class threw exception: java.io.FileNotFoundException: /Users/fechen/Repo/xxxx/spark-nrt/target/scoverage.measurements.25 (No such file or directory)

### ISSUE THREAD

**Issue by laurafchen** [scoverage/scoverage-maven-plugin#62]
HI Team

when i run my spark job with scoverage plugin added, i got below exception:
2018-07-11 01:25:37 INFO  ApplicationMaster:54 - ApplicationAttemptId: appattempt_1530585518188_0009_000002
2018-07-11 01:25:37 INFO  ApplicationMaster:54 - Starting the user application in a separate Thread
2018-07-11 01:25:37 INFO  ApplicationMaster:54 - Waiting for spark context initialization...
2018-07-11 01:25:37 ERROR ApplicationMaster:91 - User class threw exception: java.io.FileNotFoundException: /Users/fechen/Repo/xxx/spark-nrt/target/scoverage-data/scoverage.measurements.25 (No such file or directory)
java.io.FileNotFoundException: /Users/fechen/Repo/xxx/spark-nrt/target/scoverage-data/scoverage.measurements.25 (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileWriter.<init>(FileWriter.java:107)
        at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:42)
        at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:42)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
        at scoverage.Invoker$.invoked(Invoker.scala:42)
        at com.xxx.sink.DedupeAndSink$.main(DedupeAndSink.scala:30)
        at com.xxx.DedupeAndSink.main(DedupeAndSink.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$4.run(ApplicationMaster.scala:706)
2018-07-11 01:25:37 INFO  ApplicationMaster:54 - Final app status: FAILED, exitCode: 13, (reason: User class threw exception: java.io.FileNotFoundException: /Users/fechen/Repo/xxx/spark-nrt/target/scoverage-data/scoverage.measurements.25 (No such file or directory)

Can you please help out?

**Comment by laurafchen** [comment]
here goes the pom section for scoverage

 <plugin>
                <groupId>org.scoverage</groupId>
                <artifactId>scoverage-maven-plugin</artifactId>
                <version>${scoverage.plugin.version}</version>
                <configuration>
                    <scalaVersion>${scala.version}</scalaVersion>
                    <aggregate>true</aggregate>
                    <highlighting>true</highlighting>
                </configuration>
                <executions>
                    <execution>
                        <id>instrument</id>
                        <goals>
                            
                            <goal>pre-compile</goal>
                            
                            <goal>post-compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>scoverage-report</id>
                        <goals>
                            
                            <goal>report-only</goal>
                        </goals>
                        <phase>prepare-package</phase>
                    </execution>
                </executions>
            </plugin>

**Comment by gslowikowski** [comment]
@laurafchen you somehow built and deployed your application with classes instrumented by scoverage.

Sorry for very late reply. I'm closing this issue since you've probably fixed the issue. If you still need help, reopen it.
